### ISSUE TITLE
[1.16.5] Seasons mod breaks all RS processor files and causes structures to crash

### ISSUE THREAD

**Issue by tenguin** [TelepathicGrunt/RepurposedStructures-Fabric#108]
Hi,
My server has been putting out this reproducible crash upon chunk generation in the overworld, crash log also attached
[crash-2021-04-12_22.03.20-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/6300887/crash-2021-04-12_22.03.20-server.txt):

```
Description: Exception generating new chunk

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at net.minecraft.class_3785.method_16631(class_3785.java:131)
	at net.minecraft.class_3778.method_30419(class_3778.java:266)
	at com.telepathicgrunt.repurposedstructures.world.structures.BuriableStructure$Start.init(BuriableStructure.java:45)
	at com.telepathicgrunt.repurposedstructures.world.structures.BuriableStructure$Start.method_16655(BuriableStructure.java:36)
```

Other than that, 
Thank you for your work, our server really enjoys your mod ;3

**Comment by TelepathicGrunt** [comment]
Can you put on the mod called [Blame](https://www.curseforge.com/minecraft/mc-mods/blame-fabric), reproduce the crash, and give me the latest.log file instead of the crashlog file? It'll have more info as to what happened

**Comment by TelepathicGrunt** [comment]
The three structures that uses the BuriableStructure class is the icy, badlands, and snowy pyramids. All 3 I were able to find myself in testing right now.  
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/00108389a140e687b3a8fed0c92eb7c23aa7403d/src/main/java/com/telepathicgrunt/repurposedstructures/modinit/RSStructures.java#L75-L78

This seems more like another mod is doing something that is breaking Repurposed Structures and causing the structure pool to be empty. This can happen if a mod added properties to blocks in a dangerous manner that breaks processor files for structures. If the processor file fails to be parsed, it cascades the failure to the pool file and nukes all the entries from the pool which then causes the structure to crash when generating.

Blame and the latest.log file should help us know where to start looking

**Comment by tenguin** [comment]
Oh, that Blame mod is very useful!

A bit more info on the server:
The server has probably been up for around 9 months now, and during the course of that time, I routinely update the mods to their latest versions. It has probably gone through several updates of repurposed structures, along with all the other mods, so I wonder if that has caused the server to accumulate problems and errors over time.

Below is the log, sorry for wasting your time if this is an issue on my end.
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/6301134/latest.log)

**Comment by TelepathicGrunt** [comment]
Updating RS over time shouldn't cause this issue unless you have old datapacks for RS that needs to be updated as well. But that doesn't appear to be the issue. From the log, it appears that the icy dungeon processor file blew up. But looking at the JSON shown here, it matches the json that is shipped in my mod so the processor file is fine. 

This means it has to be blowing up because another mod added a property unsafely to Ice, Blue Ice, Snow Block, or Cave Air. Thus, the processor file blows up and breaks the parsing of all processor files and thus, breaks all structures. Can you share your modpack with me? I could try removing mods until I find the one that is breaking my processor files. I want to find who is doing this so I can tell them to use [Towelette](https://github.com/Virtuoel/Towelette) which allows adding properties to blocks safely that doesn't blow up structure processor files.

**Comment by tenguin** [comment]
I should have time tomorrow to try to track down the offending mod myself. I don't want to waste your time with it. Judging from your description, I think there's probably only a handful of likely candidates.

Here is the modpack however, in case you're eager to figure it out yourself:  https://drive.google.com/file/d/1UMfX7cK-6Y1SHJNuaclCrWGk6P-9hk02/view?usp=sharing

**Comment by TelepathicGrunt** [comment]
Found it. It's Seasons. I'll contact them to let them know to change how they add properties to blocks. Thank you for reporting this!

**Comment by TelepathicGrunt** [comment]
Seasons has been updated to fix this issue! Try updating seasons and see if the issue is resolved
