### ISSUE TITLE
[Question] ModUpdater and Vanguard support?

### ISSUE THREAD

**Issue by RDKRACZ** [TelepathicGrunt/RepurposedStructures-Fabric#109]
Hi, would you be interested in adding support for update checkers? I was planning to request this to a few devs but this seems quite easy to do so I might be able to make a prs for this. Asking you first since I don't want to do another spam.

Example:
https://github.com/Blobanium/Loading-Timer/blob/269cd60f53c25e494766a8b1982c5dd9bd014955/src/main/resources/fabric.mod.json#L41
Documentations:
https://gitea.thebrokenrail.com/TheBrokenRail/ModUpdater/src/branch/master/MOD_DEVELOPER.md#mod-developers
https://github.com/Ladysnake/Vanguard#curseproxy-updater

**Comment by TelepathicGrunt** [comment]
After thinking quite a bit about this, while it is good that these auto-updaters require opt-in by the mods and the user has to opt-in by downloading the autoupdaters too, it just doesn't sit right with me tbh.

 I like it more when users has to update my mods manually by downloading from curseforge or using a launcher's update button on my mod. That way people see that my mod has an update and that they can go and check my changelog for what was fixed or added. Which could be very important for the users to know.

With an autoupdater, that detail of my mod being updated gets lost which could cause issues down the line. Especially since I am planning on removing the stonebrick stronghold from my mod one Better Stronghold comes to fabric. I think users should know about that so that they will stop trying to /locate my stronghold and instead, /locate vanilla's. And if they see my changelog, they will know about Better Strongholds instead and use that mod instead to upgrade strongholds.

I'm leaning on passing up on opt-ing into the auto-updaters. I believe that should be something that a user handles. Not a mod. And I kinda do not like my mod being updated silently without user knowledge.

**Comment by RDKRACZ** [comment]
Thank you for a developer's point of view and detailed explanation. Now I see the drawbacks of these mods. Some of these mentioned vulnerabilities can even be clearly seen but I have missed them.
