### ISSUE TITLE
Failed to load v1.3.0

### ISSUE THREAD

**Issue by TheVillageid10t** [TelepathicGrunt/RepurposedStructures-Fabric#11]
https://paste.ee/p/Ifah2

**Comment by calloatti** [comment]
Same here: https://paste.ee/p/R7okW Seems to be a problem with https://www.curseforge.com/minecraft/mc-mods/better-wandering-traders maybe?

**Comment by TelepathicGrunt** [comment]
1.3.1 should fix this. I made my cartographer code run slightly later as I think trying to run my code in initialization was crashing Better Wander Trader because mod initializations can run out of order (and they register their config thing in that)

Try v1.3.1 and let me know to re-open this issue if the same crash persist!
