### ISSUE TITLE
Structures get overrun up by terrain generation

### ISSUE THREAD

**Issue by Hyperbean18** [TelepathicGrunt/RepurposedStructures-Fabric#115]
Sometimes structures doesn't remove some terrain when they generate. [pics here](https://imgur.com/a/eC4LhJN) 

I also found 2 spawners in a basalt temple. pretty sure this is unintentional

**Comment by TelepathicGrunt** [comment]
The Temples having spawners is intentional. Also, that isn’t terrain. That’s the Basalt Delta’s feature that creates basalt pillars. The issue with that feature is that it is very large and extends outside its current chunk that it it generating in. I already tried moving the temples to a generation stage after the feature and it still covers them at times. There’s really nothing more I can do about that so I’ll be closing this report. 

the outposts are not after the feature but I can move them to it but I doubt it will help much in the end. This is an issue with vanilla’s basalt feature itself. I do not want to mixin into it and cancel its generation if within my structure bounds as then it’ll create an odd looking area where the basalt feature just stops dead and create weird looking pits for the structure. There’s no good solution. 

Though funny thing is,

**Comment by TelepathicGrunt** [comment]
Yeah some have one spawner but soul sand valley temple and 1 other has 2 spawners iirc. It's been a while since I looked at the temples lol
