### ISSUE TITLE
Can you make it so that mineshafts don't float when in a cave.

### ISSUE THREAD

**Issue by QPCrummer** [TelepathicGrunt/RepurposedStructures-Fabric#118]
Could you either not make them generate at all, make them hang with chains (like 1.17), or make them make support beams. Thanks 
![2021-05-28_20 49 35](https://user-images.githubusercontent.com/66036033/120053154-ab326a00-bff6-11eb-8a28-49aa7a23297d.png)

**Comment by TelepathicGrunt** [comment]
I wont be backporting 1.17 features to 1.16. But dont worry, when I do port to 1.17, I'll look into adding the pillars and chain supports that vanilla does to my mineshafts. For now, I guess you could raise or lower the mineshafts in the config so that they are in area that tend to have more land

**Comment by TelepathicGrunt** [comment]
Update on this: holy smokes. I really can't reproduce the pillar/chain supports in my mineshafts while also obeying the other rules that mineshafts works by This is much harder than I realized and would need me to rethink the entire mineshaft stuff and it a huge amount of work.

I'll put this off till a far future update instead due to the complexity of the issue

**Comment by TelepathicGrunt** [comment]
added in v2.1.0! I had an idea on how to get the support and chains to work but had to spend time redesigning how parts of the mineshafts work to allow the pillar/chains to work. it's not perfect but it should help a ton with pics like you showed
