### ISSUE TITLE
1.17 Timeframe?

### ISSUE THREAD

**Issue by BrekiTomasson** [TelepathicGrunt/RepurposedStructures-Fabric#119]
I see a number of issues related to changes planned for the 1.17 version, such as #107, TelepathicGrunt/RepurposedStructures#96, TelepathicGrunt/RepurposedStructures#92, _et cetera_. They all seem very like reasonable changes, but some of them are also quite ambitious and seem like they might take some time.

What kind of timeframe are we expecting for a release compatible with Minecraft 1.17? Would it be possible to release an initial version with just the relevant API changes and updated mappings before working on all of these quality-of-life changes for the "real" release?

**Comment by TelepathicGrunt** [comment]
Based on the linked issue reports, it looked like you were asking about fabric RS so I moved this over to that repo. 

There's no timeframe as I just work for fun on whatever free time I get lol. However long it takes is entirely dependent on free time, the amount of codebase change, how long the config api changes and structure adjustment takes, etc.

Also, right now, Fabric API is broken and I cannot spawn any structures until this gets fixed as it will cause all my structures to crash.
https://github.com/FabricMC/fabric/issues/1478

**Comment by TelepathicGrunt** [comment]
Also, a big reason why the config changes has to be done in the initial release is because if people make a world first, and then I change the configs later, the old configs will not work anymore and all the changes people do will be reverted. And if they catch the changes too late after they generated too many chunks with the now default configs, their customized world is ruined unless they have a save from before the update. So I want to put as many breaking changes into the 1.17 initial release so there's less issues down the road for players. I'm more of a do-it-right-the-first-time kind of person unlike others who try to jump onto every snapshot/release ASAP lol

**Comment by BrekiTomasson** [comment]
Yes, it was for Fabric, sorry for opening it in the wrong repo.

And yes; you make some good points, especially the one about the config files. I didn't know structure spawning was broken, that explains why so many mods that use structures are still sitting on 1.16. 

Either way; thanks for your answer and looking forward to seeing your progress here!
