### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'repurposed_structures'!

### ISSUE THREAD

**Issue by linzexin022** [TelepathicGrunt/RepurposedStructures-Fabric#12]
Hi there, I cannot run the server and it said it was because the main reasons below:
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/4971807/latest.log)

Don't know if you can find out the problems and fix it. Thanks!

**Comment by TelepathicGrunt** [comment]
Yeah this is a bug with Repurposed Structures v1.3.0 which I see the log says you have. Please try v1.3.1 which I released shortly afterwards. The issue was I was adding the Jungle Fortress maps to the cartographer trades too early which breaks Better Wander Trader mod.

v1.3.1 can be downloaded here:
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric/files/3012513

I'll keep this issue report open for a few days so others with the crash can see my response here and updateRepurposed Structures. :)

**Comment by linzexin022** [comment]
Thank you!
