### ISSUE TITLE
Filling Up Console With Messages

### ISSUE THREAD

**Issue by SlimeBoi2006** [TelepathicGrunt/RepurposedStructures-Fabric#120]
Hello, I recently removed the repurposed structures mod form my server because I updated from 1.16.5 to 1.17. Now my console keeps filling with errors from this mod. How do I fix this?
![image](https://user-images.githubusercontent.com/84562128/121701786-1d3e9080-ca86-11eb-9b33-36d02095f5cb.png)

**Comment by TelepathicGrunt** [comment]
This is what happens when you remove any structure mod. As long as you have Fabric API still on, your world is still safe. 

The issue started with this Mojang bug. https://bugs.mojang.com/browse/MC-194811 Removing structures from worlds would break the world heavily. Fabric API fixes this by removing the missing structure references from chunks as the chunks are loaded and saved. However, Fabric API chose to keep the log spam about the missing structure starts but it should only ever appear once for the chunk and never again for that chunk. So as you play on the world, you should see less and less of that logspam until all your chunks are cleaned up by Fabric API after you explored all the existing chunks. Your world is fine. It’s just spam in the log that I cannot do anything about.

Hope this helps!
