### ISSUE TITLE
better-nether datapack and better-village-pillage datapack may cause RS's processors to crash w/ Accessing PalettedContainer from multiple threads 

### ISSUE THREAD

**Issue by SHXRKIEgg** [TelepathicGrunt/RepurposedStructures-Fabric#129]
Server crashing with latest version - repurposed_structures_fabric-2.1.2+1.17.1.jar

Crash - https://pastebin.ubuntu.com/p/5mJws6Zr5B/

Specifically Crashes in the Ocean with the repurposed_structures:pyramid_ocean Structure 

Using latest Version of [Better Minecraft [FABRIC] v4](https://www.curseforge.com/minecraft/modpacks/better-minecraft-fabric)

**Comment by TelepathicGrunt** [comment]
Mapped stacktraces: https://paste.ee/p/VxfOw
Well, the thing is, the code it got stuck on, is actually perfectly fine and should never break and it doesn't in my testing. The AirProcessor from my mod just places air in the world for structures using Legacy Jigsaw Piece mode so that air still replaces blocks: 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/70630c03bbd914965de20030a8c42c35d139a98d/src/main/java/com/telepathicgrunt/repurposedstructures/world/processors/AirProcessor.java#L39

The issue seems to be that something else is grabbing that same chunk on another thread or something as that's what this error says: `Description: Accessing PalettedContainer from multiple threads`

Does the modpack have anything that multithread's worldgen? Because if so, that's gonna break stuff as worldgen really isn't made to be multithreaded. At least, not yet by Mojang. My structure code is running in Worker-Main-1070 thread but Worker-Main-1073 thread is generating terrain noise. The main Server thread is running a command to grab all players and write nbt to a server recipe book? Maybe one of those thread is trying to access the chunk while it is being made? Dunno.

How often are you getting this crash? Is it occuring consistently at the same spot or was this just a one-time weird thing?

**Comment by SHXRKIEgg** [comment]
I believe this Datapack could be causing it - https://www.planetminecraft.com/data-pack/jjthunder-overhauled-cliffs/

The crash happens at the exact same sport every time

**Comment by TelepathicGrunt** [comment]
I tried that datapack on with just my mod and I teleported to several structures and no crash. So I put on Better Minecraft modpack and the datapack. Explored around the world and got a crash but this time, for Better Stronghold's processor:
https://paste.ee/p/lpkDg

I don't know if this is actually caused by the datapack as the datapack looks fine and just expands world height. It could be some weird edge case issue with how minecraft handles the extra height vs mods? Or maybe the modpack has a mod that is breaking everyone else's processors when height is increased. Sorry I could not help more.

**Comment by SHXRKIEgg** [comment]
All good, do you know if any performance mods cant cause it?
Like Krypton or FerriteCore or Lithium etc?

**Comment by TelepathicGrunt** [comment]
this is the first time i am seeing this issue so if someone can find out cause the conflict is or why it is occurring exactly, that would be awesome

**Comment by SHXRKIEgg** [comment]
Possibly found the issue it seems to be one of these datapacks, I have removed both and its not crashing anymore, if oyu can also test and confirm that would be appreciates!
 
https://www.planetminecraft.com/data-pack/better-nether-mobs-beta-0-1/ and https://www.planetminecraft.com/data-pack/better-illagers-v1-0/

**Comment by TelepathicGrunt** [comment]
yeah it seems to be those datapacks. Without them, I cannot get the crash. With them on, teleporting to some of yung's stronghold will quickly cause the crash. Those datapacks are using functions so it is possible one of their functions is unsafe or broken. When i got one crash, this is what the server thread was on so maybe it's a function relating to player ticks? Not sure as I never worked with datapack functions before.  Maybe this thread dump is a red-herring 
https://paste.ee/p/9skg8

Thank you! this is really good to know so I know what to check if this crash comes up again

**Comment by TelepathicGrunt** [comment]
I contacted the datapack dev on their discord so hopefully we can figure out the cause. But it is possible we might not be able to. I'll leave this issue up in case other people also get the crash

**Comment by TelepathicGrunt** [comment]
I'm trying something potentially unsafe but it is based off of what vanilla ores do. They bypass the PalettedContainer's check for threads and forces their block to be placed. If you could, can you please make a backup of your world and then give this jar a test? Let me know if it fixes the crash or if it causes any issues.
[repurposed_structures_fabric-2.3.2b+1.17.1.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7026493/repurposed_structures_fabric-2.3.2b%2B1.17.1.zip)

Hopefully this will work!

**Comment by SHXRKIEgg** [comment]
Ah nah its all good I got rid of the 1.18 Cliffs Datapack so there is no need for it but I will probs try it with Terralith in the future

**Comment by TelepathicGrunt** [comment]
New update released on curseforge that hopefully solves this issue for good
