### ISSUE TITLE
Charm causes some structures to look weird or not place blocks correctly (pyramids, witch huts, etc)

### ISSUE THREAD

**Issue by HyprGirl** [TelepathicGrunt/RepurposedStructures-Fabric#134]
Pyramids are slightly broken, they spawn with 2 "layers" of empty blocks.

![2021-07-26_21 03 50](https://user-images.githubusercontent.com/86451288/127047109-653c08d3-d4f0-4008-acbf-5928b0298efc.png)
![2021-07-26_21 08 41](https://user-images.githubusercontent.com/86451288/127047446-eff4443a-2ff5-426f-8780-87fe91c1a4e4.png)

These 2 examples show the first "layer", it generates in the middle of the 3x3 hole. In the second picture you can see it creates bad looking terrain

![2021-07-26_21 03 43](https://user-images.githubusercontent.com/86451288/127047763-a9b15cae-2e3a-4373-ac58-d5a67da57697.png)
![2021-07-26_20 55 00](https://user-images.githubusercontent.com/86451288/127047792-31c58320-d726-478f-9020-a3c672f6e847.png)

In these 2 examples you can see the second "layer", it generates at the bottom of the pyramid.
In the nbt files I saw both of these "layers" are actually filled with structure blocks so I don't really know if you can get rid of them.

Additionally the ocean pyramid's water is a bit more broken.

![2021-07-26_21 39 11](https://user-images.githubusercontent.com/86451288/127048979-5b36443e-ef29-4c6b-a811-04cb44e4ce3b.png)
![2021-07-26_21 48 07](https://user-images.githubusercontent.com/86451288/127049757-c3b8a221-9ef3-4223-8124-c3717e7fbb8f.png)

The bubble columns are stopped halfway because the water above is flowing, not source. Also there is an empty block in the middle. When the pyramid generates above ground it's still filled with water. This creates nonflowing water and just looks weird. I suggest water levels be the same as the ocean level (the same way boats are generated).

**Comment by TelepathicGrunt** [comment]
err. The layer of air you are seeing seems to be more likely to be caused by a mod compat issue. I say that as repurposed structures alone does not have this issue at all
![image](https://user-images.githubusercontent.com/40846040/127057899-6478c2c2-32b1-485a-96f6-7b1d342547b3.png)

If you can put on the mod called Blame and enter the world, you can then grab the latest.log file and share that file here as it might be able to show if the processor files blew up and what mods you have on. https://www.curseforge.com/minecraft/mc-mods/blame-fabric

In fact, whatever mod is breaking the processors is also causing that air space you saw in the ocean pyramid. So this isn't an issue on my end but I really want to find out who it is causing it so we can get them to fix their mod.

As for the ocean pyramid above ocean, I really do not like the idea of removing the water above sealevel. I may just force the pyramid to never spawn above sealevel instead.

**Comment by TelepathicGrunt** [comment]
Hmm i see what you mean here. 
![image](https://user-images.githubusercontent.com/40846040/127059229-a71c2a34-11d0-4716-b183-5ca72f2ba477.png)

iirc, i couldn't get the bubble column to fully go up because it relies on block updates which structures do not trigger at generation and so it wont iterate upward. The bubble columns is a limitation of structures so unless I find a hacky workaround for them, they will have to remain like that. The air block, wtf. I'll check that out

**Comment by HyprGirl** [comment]
Ok, I see, I'll give you the latest.log, but be warned! I have like 300+ mods, several that change world-gen (it's a work in progress modpack). I also use the experimental datapack for new world-gen. I thought that was maybe causing issues, so I disabled it and the issue still remains.
What I did: Started a new world, then tp to the nearest ocean pyramid. I hope I'm doing this right, if not I'll be happy to give you more info.

Here's paste bin: https://pastebin.com/1wninpud
If that doesn't work, the actual log file: [latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/6888480/latest.log)
And a picture because why not:
![2021-07-27_15 13 46](https://user-images.githubusercontent.com/86451288/127221337-9cc3a1a5-c940-4d0f-a128-eec2019198cc.png)

**Comment by TelepathicGrunt** [comment]
Ok so the log doesnt show any processor dying or issues even though there's clearly a problem. hmm. Are you able to export your modpack so i can test and try removing mods until I find the cause? That would greatly help me so I dont have to download every mod individually lol. Super weird tho

**Comment by HyprGirl** [comment]
Thank you for your quick replies. I really appreciate the offer, but I would rather not share the modpack. I'm going to test removing mods later today and I already have a few ideas of what could be causing the issue. Once I find it I'll be sure to tell you here!

**Comment by HyprGirl** [comment]
I found it! It's Charm, version charm-fabric-1.17-3.3.2 (the latest as of writing). Without Charm there are no issues, this really surprised me because it's so weird... especially because it's such a popular mod...

**Comment by HyprGirl** [comment]
Also regarding the bubble columns, I noticed another issue. You said it would require some kind of workaround, but still I just want to let you know.
![2021-07-28_13 49 31](https://user-images.githubusercontent.com/86451288/127345916-aac5bd47-2f69-4026-a561-763fe4106e35.png)
![2021-07-28_15 55 40](https://user-images.githubusercontent.com/86451288/127345921-a74e777e-8fec-4dfd-9d04-e3b60fd289a7.png)
As you can see the middle bubble column doesn't extend past the top of the ocean pyramid. One picture is with, the other without Charm, but there's no difference.

**Comment by TelepathicGrunt** [comment]
Like i mentioned before lol, the structure pieces places the blocks that exist in the nbt file but does not schedule a tick to them. So the bubble column block is placed but does not get told to tick and update the above water blocks to extend the column. I made a new processor that checks for bubble columns and will schedule a block tick to them so they will update all the above water automatically into bubble columns after worldgen is done. Next update will have this.

I'll test with charm and see what's up. Very odd

**Comment by HyprGirl** [comment]
I understand, just wanted to let you know. English isn't my first language so sorry if I didn't explain well. Glad you found a solution.
Also there aren't any issues posted on Charm's github regarding this.

**Comment by TelepathicGrunt** [comment]
I'm talking with Charm right now. It appears to be this mixin
https://github.com/svenhjol/Charm/blob/5f454874683710a504317423b50016f46c991130/src/main/java/svenhjol/charm/mixin/helper/AddCustomDecorationProcessorsMixin.java

Hopefully i can help them to use something else as that mixin is breaking the processors for my structures. Like the pyramids. On a cliff, the pyramid should place pillars of blocks downward from their bottom. But with Charm on, they no longer do that.

**Comment by TelepathicGrunt** [comment]
added a processor to 2.5.0 RS to add a mixin that tries to undo charm's processor. hopefully that works as a workaround until charm updates
