### ISSUE TITLE
Towelette v4.2.2/Statement v4.1.2 crashes RS processors

### ISSUE THREAD

**Issue by jklw10** [TelepathicGrunt/RepurposedStructures-Fabric#139]
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/6961679/latest.log)

repurposed_structures_fabric-2.2.0+1.17.1

**Comment by TelepathicGrunt** [comment]
Looks like this processor is failing but I correctly stated all the properties of all the blocks.
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/latest-released/src/main/resources/data/repurposed_structures/worldgen/processor_list/fortresses/jungle_fungus.json

This means you may have a mod that adds a new property to one of the blocks unsafely which causes worldgen json files to be failed to be parsed by minecraft. Since it is this specific one that died, I'm wondering if it is a property being added to mushrooms? I'll look over your modlist and see if I can find where the conflict lies

**Comment by TelepathicGrunt** [comment]
Looks like the issue is towelette

**Comment by jklw10** [comment]
i've removed both towlette and repurposed structures... and still getting a crash...
i'll see if dashloader is still trying to load them somehow.

**Comment by jklw10** [comment]
hmm.. i probably tried disabling them while the game was still on. thus not doing anything.

**Comment by TelepathicGrunt** [comment]
with RS and towelette off, can you share the crash you got? it may not be the same crash

**Comment by jklw10** [comment]
it went away after properly closing mc and re-disabling the mods
