### ISSUE TITLE
[Bug] Crash with division by zero

### ISSUE THREAD

**Issue by supersaiyansubtlety** [TelepathicGrunt/RepurposedStructures-Fabric#14]
[This crash](https://hastebin.com/ovizilirug.rb) is from when I had only FAPI and RS installed. 
[This crash](https://hastebin.com/ejiveponip.sql) is from when I had my full modset installed, which was the state the chunks generated in. 

The world seed was -8819087902084243274, coordinates (nether) are in the crash logs. 

The crash seems to happen shortly after I go into a menu, but I might just be being superstitious.

**Comment by TelepathicGrunt** [comment]
Hmm. The hastebin links expired and I no longer can see anything rip. Would you mind getting Not Enough Crashes mod on and reproducing the crash? It should make the crashlog more useful for me to track the issue down

https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes

**Comment by supersaiyansubtlety** [comment]
Ok, so in trying to reproduce the crash I learned a little more about it. 
I couldn't reproduce it in the same world as before. Instead I re-generated the world, and then the crash started occurring either as the world was loading or soon after it had loaded. 

Anyways, these are pastebin links, maybe they'll last longer?

[crash](https://pastebin.com/7Nshze5G) with modset
[crash](https://pastebin.com/xtY0MBdu) with only RS, FAPI, and NEC

**Comment by TelepathicGrunt** [comment]
Ok now I know where the crash is happening. Go to the config for repurposed structures. Is any structure's spawnrate set to 0? if so, which ones?

**Comment by supersaiyansubtlety** [comment]
Ah, that would be `netherStrongholdSpawnrate = 0`
But not sure why that was happening when I spawn in the overworld...

**Comment by TelepathicGrunt** [comment]
Minecraft is very strange with how it handles structures in chunks and all with structure starts even when no structure is in the chunk. Though I'm curious as to how the spawnrate for it got set to 0 as I specified that the range has to be between 1 and 1001 with autoconfigu. 

Was the config file edited directly or through the GUI? It might be a bug with autoconfigu which is why I am asking. But yeah, glad I was able to help you with this. :)

<https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/81c32312eec6c17b338c8cca3f365db210ac7bde/src/main/java/com/telepathicgrunt/repurposedstructures/configs/RSStrongholdsConfig.java#L84-L89>

**Comment by supersaiyansubtlety** [comment]
Oh, heh, oops. Yeah I set it manually and didn't notice the comment about 1-1001. My bad. 
Still probably best to have a check and put a warning in the log?
Also why does 1001 represent no spawning rather than 0?

**Comment by TelepathicGrunt** [comment]
It's because structure spawnrates are based on distance in minecraft. A spawnrate of 50 means the structure spawns no more than 50 chunks apart from each other (and cannot be closer than 37 chunks as I set the minimum separation to 3/4th the spawnrate). So as the spawnrate gets closer to 1, the density of the structure in the world increases with 1 being every chunk able to spawn the structure. So that's why I set 1001 to turn them off as past 1000 chunks, that's super far and kinda ridiculous lol. 

I'll ask autoconfigu to see if they can parse and sanitize configs in case they were manually edited. Thank you!
