### ISSUE TITLE
[1.16.5] When Dungeons Arise - Fabric!

### ISSUE THREAD

**Issue by ghost** [TelepathicGrunt/RepurposedStructures-Fabric#142]
After add the WDA mod, game sometimes crashed.
possibly a modification conflict, can you look at it?

logs: https://pastebin.com/SLtDJScT

Thanks :)

**Comment by TelepathicGrunt** [comment]
This isn’t a dungeons arise issue. See the line that says null pointer error due to a method called setSmokey? The good news is I know what mod is the problem as this was reported before here: https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/138

If you update the Smokey mod, the issue should go away. Hope this helps!

**Comment by ghost** [comment]
Great information, thanks for help :)
