### ISSUE TITLE
Full Slabs adds properties to vanilla blocks unsafely and crashes RS structures

### ISSUE THREAD

**Issue by Micalobia** [TelepathicGrunt/RepurposedStructures-Fabric#144]
A mirror of Micalobia/Full-Slabs#25, just so both parties are aware of the issue. The error does proc with just RepurposedStructures, so it isn't some other mod clashing.

It seems to have issues loading [nether_randomize.json](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/d8a2435f753936d71d83bc23f7b3601bf933294e/src/main/resources/data/repurposed_structures/worldgen/processor_list/cities/nether_randomize.json), I have no idea what the reason could be as it doesn't fully crash and give a useful error.

**Comment by TelepathicGrunt** [comment]
Oh no. Not another mod adding properties unsafely to vanilla blocks lol. Basically, the gist is that if you use mixins to directly add a property to a vanilla block, any worldgen json file that uses that block will blow up because the json is now missing that new property added. This would mean that Full Slabs will blow up datapacks and mods that use slabs in their worldgen json files where it requires all properties to be specified. This would have to be fixed on Full Slabs's end by utilizing the mod called Statement as that mod allows people to add new properties to blocks safely. I'll comment on the issue report on their github so they know how to fix this

**Comment by TelepathicGrunt** [comment]
@Micalobia  oh wait, you're the developer lol. Oops my bad. 
But yeah, you'll want to remove these mixins that inject properties into slabs:
https://github.com/Micalobia/Full-Slabs/blob/a96cd9c8dc276c3671e8557fd0af6d3229e9f3a5/src/main/java/dev/micalobia/full_slabs/mixin/block/SlabBlockMixin.java#L65-L73

And instead, use the Statement library to add the properties to the blocks: 
https://www.curseforge.com/minecraft/mc-mods/statement

The reason why the json files blow up is because the Blockstate Codec used for many worldgen json files like here, requires every single property to be specified. So when a mod adds a new property unsafely, the codec sees the json file is missing that property, chokes, and then blows up. The processor file fails to be parsed which causes the error you saw.
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/d8a2435f753936d71d83bc23f7b3601bf933294e/src/main/resources/data/repurposed_structures/worldgen/processor_list/cities/nether_randomize.json#L58-L64

Statement found a way around this issue by finding a special place to inject properties without causing the blockstate codec to explode for existing json files. You can ask Virtuoel on how to use statement or check out Towelette or 
Better Slabs (by IEilux) for how to use Statement library. 

But yeah, don't feel bad about this. The main reason I know what the issue was instantly was because I had many run ins with other mods trying to mixin to add properties to blocks and not realize they blow up datapacks now lol. It is a common issue but thank god for Statement providing a solution.

**Comment by Micalobia** [comment]
In retrospect, that makes a whole lot of sense, thank you for the very detailed reply, it was immensely helpful. Extremely grateful you had experience as well, that would have been a nightmare to debug because of the very vague error. I will close this as soon as I patch it, thank you for your help 😄
