### ISSUE TITLE
Compatibility with Yung's Better Strongholds (increaseWeightLimit)

### ISSUE THREAD

**Issue by davidalb97** [TelepathicGrunt/RepurposedStructures-Fabric#145]
While using Repurposed Structures with Yung's Better Strongholds, the following warning shows up on server:

```
[main/WARN]: @ModifyConstant conflict. Skipping betterstrongholds.mixins.json:StructurePoolMixin->@ModifyConstant::betterstrongholds_increaseWeightLimit(I)I with priority 1000, already redirected by repurposed_structures.mixins.json:structures.StructurePoolMixin->@ModifyConstant::repurposedstructures_increaseWeightLimitProd(I)I with priority 1000
```
From what I understand, both mods are attempting to do the same thing, but Yung's Better Strongholds mixin is the one being disabled.
Is this mod compatible with Yung's Better Strongholds?

Modlist:
*  betterstrongholds@1.17-1.1.1
*  fabric@0.40.1+1.17
*  repurposed_structures@2.3.4+1.17.1
*  yungsapi@1.17-Fabric-16

[log on pastebin](https://pastebin.com/1fUvPRRA)

[Opened the same issue on Yung's Better Strongholds](https://github.com/yungnickyoung/YUNGs-Better-Strongholds/issues/41)

**Comment by TelepathicGrunt** [comment]
This mod is compatible with better strongholds. That mixin is not a problem at all. Me and better strongholds made that mixin so that if the spot already was mixined to increase the pool entry weight limit, the other mod’s mixin is skipped like it says there in the log. No functionality is lost as our mixins do the same thing.

I’m gonna close this issue report. Is there any issue you found or were you just combing through the log for anything?

**Comment by TelepathicGrunt** [comment]
This mod is compatible with better strongholds. That mixin is not a problem at all. Me and better strongholds made that mixin so that if the spot already was mixined to increase the pool entry weight limit, the other mod’s mixin is skipped like it says there in the log. No functionality is lost as our mixins do the same thing.

I’m gonna close this issue report. Is there any issue you found or were you just combing through the log for anything?

**Comment by davidalb97** [comment]
I found no issue whatsoever, just like you said, I was just combing through the log for any problems.

**Comment by TelepathicGrunt** [comment]
Ah alright. But don’t hesitate to open a new issue report if you do find an issue with my mod!
