### ISSUE TITLE
Flattening of Terrain for Village Generation

### ISSUE THREAD

**Issue by StopTakingAllTheNames** [TelepathicGrunt/RepurposedStructures-Fabric#15]
I've seen a lot of custom villages in other biomes where the houses or structures are perched in high places unreachable for villagers, or sometimes they are entombed in other structures such as giant boulders or nether structures. Is there a way to possibly flatten the terrain on which they spawn?

**Comment by TelepathicGrunt** [comment]
This is due to how Jigsaw structures works and there's nothing that can be done about it. Vanilla Village will be broken up by mountains all the time like this:
![image](https://user-images.githubusercontent.com/40846040/88922145-b6353600-d23d-11ea-986c-e10e43b8dfe5.png)

The reason for this is because the roads are terrain matching and houses are generated at the edge of the road which is at the highest land height.

The only other option available for roads is making them rigid but that makes the village completely flat and will cut into mountains and place houses underground in mountains. It would also make houses be on floating land when going away from the mountain as well.

The Nether Villages however have rigid roads because terrain matching would place the villages on the bedrock roof of the Nether. It looks ok for the Nether as it is a very enclosed space and hard to see far. However, this is why the Nether villages are completely flat. 

Now one could think that, hey, why can't you just make roads like ramps or something to make it not flat? And my response to that is, I tried. This is the result lol. Vanilla's system for adding land around the base of structures will not work for slanted roads or raised structures at all. It just creates weirdly floating roads and houses with no land.
![image](https://user-images.githubusercontent.com/40846040/88922603-555a2d80-d23e-11ea-8a8e-0e482d015cb7.png)

Then there's the features like trees and stuff that are placed in the houses. I keep the villages in the Surface Structure generation stage to match vanilla village which means stuff like crimson's trees will generate after the village is made which is why they get inside the houses (but I think that looks fine and helps keeps the nether village houses more nether-like and corrupted). 

Though the boulder thing is something I tried to really fix and couldn't The boulders in the hill's giant tree taiga biome are so large that no matter which generation stage I put the Giant Tree Taiaga village in, the boulders still will get inside the houses. That's why I only put the Giant Tree Taiga village in the non-hill's Giant Tree Taiga biomes and the boulders in the hills form. I tried to keep the two separate. However, when added to modded biomes, the two will be put into the same biome causing this issue so you should disable one of the two's add____ToModdedBiomes config for that.

Hence why the current Village system is the best I can do. Really it's on Mojang to improve the jigsaw structures to better accommodate the land around it as I do not have the time nor knowledge on how to make an entirely new jigsaw system that handles height variations better (and even then, a village going into a cliff is still gonna get completely buried if it can't directly move to the top of the cliff)
