### ISSUE TITLE
Cyanide states pool weights are too high despite it not an issue for RS

### ISSUE THREAD

**Issue by BrekiTomasson** [TelepathicGrunt/RepurposedStructures-Fabric#154]
I'm getting a number of warnings relating to weights being used in a number of JSON files under your `worldgen/template_pool`. Stuff like:

```
Value 1000 outside of range [1:150] at index 0
	at: "elements"
	at: file "data/repurposed_structures/worldgen/template_pool/mineshafts/birch/main_start.json"
	at: data pack Fabric Mods
Value 700 outside of range [1:150] at index 0
	at: "elements"
	at: file "data/repurposed_structures/worldgen/template_pool/mineshafts/birch/main_step.json"
	at: data pack Fabric Mods
Value 299 outside of range [1:150] at index 1
	at: "elements"
	at: file "data/repurposed_structures/worldgen/template_pool/mineshafts/birch/minecarts.json"
	at: data pack Fabric Mods
```

It seems the weight of indivudal elements cannot be set to more than 150, and several of them are set far higher than that.

**Comment by TelepathicGrunt** [comment]
This is actually not an issue when cyanide is not on. That’s due to cyanide using the vanilla weight limit of 150 and saying the weights are too high when I already used mixins to increase the weights to 5000 instead of 150. https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/tree/latest-released/src/main/java/com/telepathicgrunt/repurposedstructures

You’ll find that Better Strongholds does the same thing to bypass that 150 limit. But our mixins does not apply to Cyanide which will try to evaluate our files based on the 150 limit even though it isn’t an issue when it is just our mods running without cyanide. 

I’ll leave this up for a bit in case others are confused too

**Comment by alcatrazEscapee** [comment]
Should no longer be an issue as of https://github.com/alcatrazEscapee/cyanide/commit/d3ed4dbf00a682d25a4e8651dcfc60008faac821 with Cyanide 1.2.2+

**Comment by TelepathicGrunt** [comment]
Nice! I’ll close this now
