### ISSUE TITLE
Better Wandering Trader crash

### ISSUE THREAD

**Issue by ReiNAce** [TelepathicGrunt/RepurposedStructures-Fabric#157]
Minecraft is crashing at startup. Idk why. Attached is the crash logs. I am using MultiMC as MC loader in Fabric 0.12.5 for MC 1.17.1.
Please help. Thanks
[crash-2021-11-23_15.06.13-client.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7586260/crash-2021-11-23_15.06.13-client.txt)

**Comment by ReiNAce** [comment]
I just installed no_null_processors and here is a new crash report.
[crash-2021-11-23_15.17.12-client.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7586302/crash-2021-11-23_15.17.12-client.txt)

**Comment by TelepathicGrunt** [comment]
Caused by: java.lang.NullPointerException: Cannot read field "identifier" because "net.hyper_pigeon.better_wandering_trader.BetterWanderingTraderMod.CONFIG.invisibleTradeFactory.array[<local1>]" is null
	at net.minecraft.class_3853.<clinit>

It appears better wandering trader may be the problem. I am using fabric API’s hook for adding new trades to wandering traders and villagers. The only way it can really crash is if another mod messes with trades in a way that crashes Fabric API. Please remove better wandering trader mod and see if the issue goes away or reset their config as it could a broken config file.

**Comment by ReiNAce** [comment]
ok thanks. I removed the wandering trader mod and it works. Can your mod be applied to an existing world or should I create a new world to view the structures? I haven't explored too much before I applied the mod so the chunks weren't loaded yet beyond my base area

**Comment by TelepathicGrunt** [comment]
Repurposed Structures will only spawn the new structures in ungenerated chunks you have not explored yet. So if you add it to an existing world, you will need to explore further out but yes, you will eventually find the new structures. Hope this helps!
