### ISSUE TITLE
Odd strips of wood planks near Savanna Village

### ISSUE THREAD

**Issue by RubyRezal** [TelepathicGrunt/RepurposedStructures-Fabric#160]
Location: NW of spawn, Seed: -1166828785

This happens with no other mods loaded except Fabric API and Cloth Config API

![2021-11-30_11 37 09](https://user-images.githubusercontent.com/1816386/144089072-11b8bc55-2529-46a3-b3bc-461496023a4f.png)

**Comment by TelepathicGrunt** [comment]
This is actually a normal artifact with how I raised RS mineshafts spawn height ranges to allow them to spawn in mountains. The only think I need to change here is make sure the floor doesn’t place planks due to grass but otherwise, it is normal to see parts of the bottom of the mineshaft if it spawns just above terrain. Maybe I can see about adding a check to lower it if land is too low.

**Comment by TelepathicGrunt** [comment]
fixed in v3.1.2
