### ISSUE TITLE
Dependency warning in server console at startup

### ISSUE THREAD

**Issue by ghost** [TelepathicGrunt/RepurposedStructures-Fabric#163]
Mod 'Repurposed Structures' (repurposed_structures) 3.1.6+1.18.0 recommends version 1.0.0 or later of no_null_processors, which is missing! - You should install version 1.0.0 or later of no_null_processors for the optimal experience.

I found no  null processors on curseforge but it doeesntt have a 1.18 version, there is also no mention of this dependency on the RS curseforge page

**Comment by TelepathicGrunt** [comment]
I’ll remove it next update. Or update no null processor if the issue it has still exists in 1.18. Will need to be investigated

But you can just ignore it for now

**Comment by TelepathicGrunt** [comment]
no null processor updated to 1.18 now. Issue still existed in 1.18

**Comment by ghost** [comment]
@TelepathicGrunt Ok I will install  nnp on my server. Just curious what feature it enables in RS and if you will at it to the curseforgee page of RS so people know to get it? Thanks

**Comment by TelepathicGrunt** [comment]
I can mark it as an optional dependency on curseforge. Basically, it doesn’t actually enable anything in RS. It’s more to fix a very rare and difficult vanilla bug to diagnose that started in 1.17+ Minecraft.

the bug is that if a structure with json processor lists (RS has this) is on and the player manages to make two different chunks with structure pieces generate at the very exact same time, the game can crash saying the processor list is null. This seems to happen more often when pregenerating a world or having multiple players exploring several dimensions at the same time. 

Hence No Null Processor being suggested as it should fix that bug that very few people seem to get.
