### ISSUE TITLE
After deinstall log spam

### ISSUE THREAD

**Issue by f0kx** [TelepathicGrunt/RepurposedStructures-Fabric#182]
Hallo i installed your mod but I need to deinstall it again

Now when I join my console get spammed with

 [Server thread/ERROR]: Unknown structure start: repurposed_structures:outpost_giant_tree_taiga
[02.02 11:33:50] [Server] [Server thread/ERROR]: Unknown structure start: repurposed_structures:outpost_end
[02.02 11:33:50] [Server] [Server thread/ERROR]: Unknown structure start: repurposed_structures:outpost_oak
[02.02 11:33:50] [Server] [Server thread/ERROR]: Unknown structure start: repurposed_structures:mineshaft_nether

Is there a way to get rid of this?

Have a nice day

**Comment by TelepathicGrunt** [comment]
This is going to always happen when removing any structure mod. The references to the structure remains in the chunks and the game logspams as it removes it over time. It will not have any negative effect on gameplay in 1.18.1 (Mojang fixed the gameplay issues from missing structures in 1.18). Fabric API chose to let the logspam continue to happen instead of silencing it. 

I would recommend just ignoring the spam or try finding a mod like shut up console and see if it works on 1.18.1 https://www.curseforge.com/minecraft/mc-mods/shut-up-console

There is this for removing the structure references but it says it is having issues in 1.18.1. https://github.com/Nyveon/MCStructureCleaner

Otherwise, the logspam when removing any structure mod is just something you’ll have to live with or see if you can convince the Fabric API folks to change their mind and silence the logspam.
