### ISSUE TITLE
Add config options to disable villager trades

### ISSUE THREAD

**Issue by CamperSamu** [TelepathicGrunt/RepurposedStructures-Fabric#185]
I use a different mod to add map trades to villagers and I'd like to disable RS custom map trades.

**Comment by CamperSamu** [comment]
Ok so I found the time to check the code from my phone, this should be easy enough.
The config is flexible so it's just a matter of adding a new config module and adding a && tradeconfig.XTradeEnabled.

Once I get to code it I'll open a PR.

**Comment by TelepathicGrunt** [comment]
Just fyi, I’m pretty sure mods like kubejs or craft tweaker let’s you remove my maps from trades. 

I personally rather not have to add config entries for every structure because that’s a can of worms of hell. If I have one for turning off, then people will want one for adding other rs structures maps. Which then leads to about 100 new config entries which is difficult for me to maintain. 

I’ll consider making say a new config that is a map similar to how the structure mob spawn config works but try trade modifying mods first for now.

**Comment by TelepathicGrunt** [comment]
v3.3.10 now has config/repurposed_structures-fabric/map_trade_configs.json5 config file that allows for adding/removing map trades in a more sustainable way for me and offers lots of options for players to configure. Do note, I do not have a way to detect what structure is disabled by the other configs. So if you disable an RS structure, you'll have to edit the map config to remove that map yourself. (otherwise the map just turns into an empty map for trade)
