### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by BigSmoke1425** [TelepathicGrunt/RepurposedStructures-Fabric#202]
Hey, i writed you with the same problem but with the nether.
now after 2-3 weeks without updating my server is crashing now in the overworld.
What can i do? 
MC 1.18.2

here is the crash log:
https://paste.corebot.dev/izuyinaqej.php

**Comment by BigSmoke1425** [comment]
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/199

**Comment by TelepathicGrunt** [comment]
That doesn't seem to show any info nor look like a normal crash report. All it says is 
java.lang.Error: Watchdog
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at net.minecraft.server.dedicated.DedicatedServerWatchdog.run(DedicatedServerWatchdog:52)
	at java.lang.Thread.run(Thread.java:833)
	
Could try removing Not Enough Crashes and then give me the latest.log when it crashes again. I don't try crash reports to show all the relevant info as much as latest.log does.

**Comment by BigSmoke1425** [comment]
hello, here is my latest log: https://paste.corebot.dev/wasivazenu.md

**Comment by TelepathicGrunt** [comment]
`Caused by: java.lang.IllegalStateException: Trying to access unbound value 'ResourceKey[minecraft:worldgen/processor_list / repurposed_structures:pyramids/generic]' from registry Registry[ResourceKey[minecraft:root / minecraft:worldgen/processor_list] (Stable)]`

When you downloaded the OldProcessor datapack, how exactly did you apply it to the game? Because the crash stacktrace says it cannot find `minecraft:worldgen/processor_list / repurposed_structures:pyramids/generic`. But the resource pack is correct 
[Repurposed_Structures-OldProcessors.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/8835770/Repurposed_Structures-OldProcessors.zip)
![image](https://user-images.githubusercontent.com/40846040/171954380-1e8e11cc-cc4e-44ab-aaef-bea5e0d8dbb6.png)

~~Though the original report also show that. Honestly, I would suggest not trying to upgrade old modded worlds to newer mc version. It's always going to be a pain and it isn't worth it trying to fix these issues. Especially this as idk what is wrong with the chunk's data to be using an incorrectly formatted resourcelocation or if another mod is breaking that to the point the OldProcessor datapack no longer works. Either way, I got nothing left sorry~~

Actually, lets make sure your datapack is actually applied correctly first

**Comment by BigSmoke1425** [comment]
should i place the two files in the datapack folder or in the data folder?

**Comment by TelepathicGrunt** [comment]
No, you place Repurposed_Structures-OldProcessors.zip entirely into the world’s datapack folder that’s in the world’s save folder. So it would be worldname/datapacks/Repurposed_Structures-OldProcessors.zip

This for sure should load the datapack properly. To check in-game, there’s a command to list what datapacks are on and active. I believe it is `/datapack list enable`. If you can see Repurposed_Structures-OldProcessors in that list, it is working and loaded in correctly

**Comment by BigSmoke1425** [comment]
okay thanks, i will trying it now

**Comment by BigSmoke1425** [comment]
its now working, thanks
