### ISSUE TITLE
[Datapack] Village spawn too many Foresty Bench fro "More Villagers" mods

### ISSUE THREAD

**Issue by ardissaps** [TelepathicGrunt/RepurposedStructures-Fabric#203]
Like there is 5 Forestty Bench on 1 taiga Village as example. Is it intentional? Please investigate, thanks in advance

**Comment by TelepathicGrunt** [comment]
Taiga village? That’s a vanilla village. Not an RS village. The datapack only adds More Villager’s houses to RS villages and makes them not spawn more than once in a single rs village. 

More Villagers handles spawning in vanilla villages themselves even without my datapack. Please let me know if this is the case or if you meant a different village and one that’s actually from rs. (If you show a picture of the village, I can let you know if it is a vanilla village or an rs village)

**Comment by ardissaps** [comment]
> Taiga village? That’s a vanilla village. Not an RS village. The datapack only adds More Villager’s houses to RS villages and makes them not spawn more than once in a single rs village.
> 
> More Villagers handles spawning in vanilla villages themselves even without my datapack. Please let me know if this is the case or if you meant a different village and one that’s actually from rs. (If you show a picture of the village, I can let you know if it is a vanilla village or an rs village)

I see, so it "more village"  side need to be tuned? Sorry! I'll report again if happen on RS village. Thx for fast respone :p

**Comment by TelepathicGrunt** [comment]
Yeah. Check their config. They may have an option to lower the weight of their houses so it has a smaller chance of spawning. It might help reduce the amount of their houses that spawns. It’s basically chance based which is why you may even see vanilla villages with multiple blacksmiths or churches. Though 5 of one workstation house is a bit excessive lol.

I’ll close this then. Maybe I’ll let them know about a way to limit their houses maximum spawn count per village using a mixin
