### ISSUE TITLE
1.16.2 Server Crash - RSIglooPieces$Piece.method_14931

### ISSUE THREAD

**Issue by Katorone** [TelepathicGrunt/RepurposedStructures-Fabric#21]
https://pastebin.com/WVXG98p1

**Comment by TelepathicGrunt** [comment]
This is actually a crash caused by Gunpower mod. You can remove Gunpower Sleepvote mod until they push a bugfix for the base gunpowder mod. I have a bug report already made to them here that you can watch to know when the crash fix is released. :)
https://github.com/Gunpowder-MC/GunpowderSleepVote/issues/1

**Comment by martmists** [comment]
Fixed by us, can be closed.

**Comment by TelepathicGrunt** [comment]
Nice! Marking as resolved

**Comment by Katorone** [comment]
Thanks !
