### ISSUE TITLE
Failed to create valid structure

### ISSUE THREAD

**Issue by BearfootNick** [TelepathicGrunt/RepurposedStructures-Fabric#213]
This didnt crash anything and is not really an issue for us, but it asked to report so here we are.

02.07 18:27:46 [Server] INFO -------------------------------------------------------------------
02.07 18:27:46 [Server] INFO Repurposed Structures: Failed to create valid structure with all required pieces starting from this pool file: repurposed_structures:villages/oak/town_centers. Required pieces failed to generate the required amount are: [waystones:village/common/waystone=1]
02.07 18:27:46 [Server] INFO Make sure this structure's size in the config (if it has one) is not set too low.
02.07 18:27:46 [Server] INFO Also make sure the max height and min height for this structure in the config (if it has one) is not too close together.
02.07 18:27:46 [Server] INFO If min and max height is super close together, the structure's pieces may not be able to fit in the narrow range and spawn.
02.07 18:27:46 [Server] INFO Otherwise, if the min and max height ranges aren't close, and structure size isn't super small like 1 or 2, and this message still appears,
02.07 18:27:46 [Server] INFO please report the issue to Repurposed Structures's dev with latest.log file!

There isn't anything else in the logs referencing this. but I can Link if you would like

We love your mods! Thank you so much for the content.

**Comment by TelepathicGrunt** [comment]
Which Waystone mod are you using as there’s two on fabric. And what Mc version and Waystone version?

**Comment by BearfootNick** [comment]
> Which Waystone mod are you using as there’s two on fabric. And what Mc version and Waystone version?

My apologies we are using:

Fabric 13.3 1.18.1
Waystones mod 1.18.1 9.0.4 BlaytheNinth 

https://www.curseforge.com/minecraft/mc-mods/waystones

**Comment by TelepathicGrunt** [comment]
I am no longer supporting older mc version to reduce my workload. Iirc, I PRed a change for the RS compat into waystones in 1.18.2 to use my json compat system. Before then in older waystones, the compat was done through code I originally PRed but had a typo or something and caused the compat to not work. Hence why it was fixed in 1.18.2 and newer.

Pic from 1.19 I just tested.
![image](https://user-images.githubusercontent.com/40846040/177020353-4d536039-6231-49a5-b026-bdcba83e4b2d.png)

I'll close this now as the compat is currently working on 1.19
