### ISSUE TITLE
Using the portal in an Ancient End City makes multiple return gateways.

### ISSUE THREAD

**Issue by Auzathoth** [TelepathicGrunt/RepurposedStructures-Fabric#223]
RS 6.2.0
MC 1.19.2
Quilt 0.17.2-beta.2

When using the portal in an Ancient City in the end multiple times, a new return gateway is created each time, stacked on top of the previous one:

First use:
![2022-08-09_18 16 01](https://user-images.githubusercontent.com/83247784/183716219-13571d80-0a0c-4136-88e4-07f928a16a53.png)

Second use:
![2022-08-09_18 16 13](https://user-images.githubusercontent.com/83247784/183716261-e83f37cf-bd2e-44a3-9a9b-6aeb5c1d7265.png)

After 5 uses...
![2022-08-09_18 24 55](https://user-images.githubusercontent.com/83247784/183718226-1f0b3a7e-3030-4c07-a8b3-7326ec7c958f.png)

**Comment by TelepathicGrunt** [comment]
That’s vanilla behavior it seems for new end gates way not spawned by vanilla. I don’t think I’ll be able to fix that without breaking other end gateway behavior. Might just have to be something to live with

**Comment by TelepathicGrunt** [comment]
Just released a new update to fix this. Turns out, I can hijack End gateway's ExitPortal nbt and set a new destination myself. Doing so will make the portal not spawn an additional end gateway it seems. I set it so that the End Ancient City's End gateway teleports you to 0,0 coordinate in the End Dimension at topmost land.
