### ISSUE TITLE
Nether corruption on server after some time

### ISSUE THREAD

**Issue by Monster-Zer0** [TelepathicGrunt/RepurposedStructures-Fabric#29]
after some time and a reboot later, when trying to startup the world, the nether becomes corrupt and prevents bootup until I remove the nether dimension folder in worlds.

[Log is here](https://p.lab717.com/obiqureloq.sql)

**Comment by TelepathicGrunt** [comment]
marking this as resolved as the issue was discussed in discord. The issue was vanilla is not threadsafe when loading chunks in multiple worlds and so, has a chance of crashing when two chunks loads any structure at the same time. including vanilla structures. Solution? keep poking fabric api to fix this lmao
