### ISSUE TITLE
Nether Structures cannot be found with /locate if BetterNether is on

### ISSUE THREAD

**Issue by SekoiaTree** [TelepathicGrunt/RepurposedStructures-Fabric#38]
I've been flying around checking out the new structures using /locate, and I went into the nether to see those. I tried using /locate, but it immediately returns "Could not find that structure nearby". I am using BetterNether, but I have found a nether mineshaft which also doesn't get found with /locate, meaning it is an issue with this mod. Anyway, I'm pretty sure it's because the structures are marked as only spawning in the overworld, meaning it immediately returns to save time. You'll probably need to do the same thing as you did for the end shipwrecks.

**Comment by CorgiTaco** [comment]
Are you using their latest version? In their changelog it says they fixed locate for one of their structures so probably all were fixed aswell. https://www.curseforge.com/minecraft/mc-mods/betternether/files/3082855

**Comment by SekoiaTree** [comment]
I'm using the latest curseforge version for sure, because I downloaded it today,

**Comment by TelepathicGrunt** [comment]
Actually, /locate operates on the chunkgenerator/biome source so it would be on BetterNether's side if they are not handling the dynamic biome registry properly in their Biome Source. I do not mark a structure 'for overworld' as instead, I just add it to the biomes it should spawn in is all. I do an extra thing of adding the structure spacing to all chunk generators so technically, the nether structures can spawn in any dimension if you can add them to the other dimension's biomes.

So there's is 1 thing to check to confirm my suspicion of what the issue is. Can you turn up the spawn rates of the Nether Pyramid structure to 1, restart the game, and then go into the better nether? if the badlands pyramids are spawning but /locate isnt working, then it is better nether's side and i'll check out their code to help them fix it

**Comment by TelepathicGrunt** [comment]
Just tested and yeah, mu structures are spawning and my suspicions are confirms. better nether's biome source is not using the right biome registry for the locate command to work. I'll open an issue report to them

![image](https://user-images.githubusercontent.com/40846040/97065171-dabd5780-1579-11eb-835d-4d145142e257.png)

**Comment by SekoiaTree** [comment]
Ah interesting. I'll close this issue then.

**Comment by TelepathicGrunt** [comment]
Actually, I'm gonna leave this open until better nether patches the bug. That way others with the same questions or issue can see this report and get up to speed on what is happening. :)

Mainly because I know how frustrating it can be to try and find reports of issues lol

**Comment by SekoiaTree** [comment]
Fair enough :+1:

**Comment by TelepathicGrunt** [comment]
better nether fixed this in 4.1.6 now :)

**Comment by SekoiaTree** [comment]
Great, thanks!
