### ISSUE TITLE
Prevents Stronghold Generation (or breaks /locate)

### ISSUE THREAD

**Issue by supersaiyansubtlety** [TelepathicGrunt/RepurposedStructures-Fabric#39]
I'm on MC 1.16.1, RS 1.4.6, FAPI 0.18.0, and for testing I used no other mods. 
If I create a world with with this setup and run `/locate stronghold` I get 'Could not find that structure nearby'. 
I've tried both creating a new world and re-creating worlds that had a stronghold without RS installed. 
Here's my setting file: [repurposed_structures-main.toml](https://pastebin.com/BUnLfUfe)

I suspect this is related to `netherStrongholdSpawnrate = 1001`

**Comment by TelepathicGrunt** [comment]
By default, repurposed structures replaces the vanilla stronghold with its own. Do /locate repurposed_structures:stronghold_stonebrick to find the stonebrick stronghold. The netherStrongholdSpawnrate = 1001 means nether strongholds will not spawn is all.

**Comment by supersaiyansubtlety** [comment]
Does it make eyes of ender work with the replacement structure? 
My friend and I went out 7000 blocks or something following the eyes and didn't reach a stronghold.

**Comment by supersaiyansubtlety** [comment]
Hm, in a test world the eyes seem to point to the replacement structure, does RS change the distance from spawn that strongholds spawn?

**Comment by TelepathicGrunt** [comment]
The eyes should detect any of the three kinds of strongholds due to this mixin
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/master/src/main/java/com/telepathicgrunt/repurposedstructures/mixin/EnderEyeStrongholdLocatingMixin.java

annnd now I see you mentioned you were on 1.16.1. Oops. Yeah I stopped supporting older versions. I am not sure if 1.16.1 is when I added the limit that RS strongholds cannot be within 1600 blocks of world origin. But yes, RS Strongholds use the traditional structure placement algorithm instead of vanilla's stronghold placement. This is because vanilla's original system for strongholds is widely inefficient and checks every biome in 100 chunk radius to see if a spot can spawn a stronghold. It's horrible lol. So instead, RS Stronghold will just use the regular structure spacing which is controlled by `stonebrickStrongholdSpawnrate = 85`. This means each stonebrick stronghold cannot be more than 85 chunks from each other and the minimum distance they can be is 59 chunks (I had min distance set to 70% of maximum distance. I reduced it to 50% in 1.16.3 for more varied placements)

**Comment by supersaiyansubtlety** [comment]
So does that mean that going 7000 blocks without finding a stronghold shouldn't be possible? Maybe this is a mod interaction?

**Comment by TelepathicGrunt** [comment]
possibly. You can turn off the stonebrick stronghold in the config which will make vanilla strongholds spawn again. You can just play with vanilla strongholds for now. If you find this is still an issue in 1.16.3, let me know!

**Comment by supersaiyansubtlety** [comment]
Ok, thanks foe the help.
