### ISSUE TITLE
redstone dust dots are crosses

### ISSUE THREAD

**Issue by RyanCR03** [TelepathicGrunt/RepurposedStructures-Fabric#58]
the singular redstone dots in the nether structures(which i assume are supposed to be in dots) are in crosses, a solution to this would be to right  click the redstone crosses to turn them into dots.

**Comment by TelepathicGrunt** [comment]
This is intentional actually. I found that the dots look bad for representing blood streaks so I kept them as crosses. Though here's a datapack that I quickly put together that you can slap on. If it works, it should convert all the redstone wires in crimson and warped villages to dots for you. The datapack should work as I just added an entry into the village's processor json files to detect redstone wire and change the blockstate upon generation.

[Repurposed_Structures-Redstone_Dot.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/5612528/Repurposed_Structures-Redstone_Dot.zip)

**Comment by RyanCR03** [comment]
Ooh I thought there were supposed to me blots instead of streaks
