### ISSUE TITLE
[Suggestion] Settlements

### ISSUE THREAD

**Issue by RyanCR03** [TelepathicGrunt/RepurposedStructures-Fabric#62]
we have villages in the nether inhabited by piglins but what if we have settlements that are inhabited by villages? my Idea is to have villages that are in the nether and end that have villages along with a portal back to the overworld.

**Comment by RyanCR03** [comment]
and the end ones could have an unlit nether portals because they're trapped in the end.

**Comment by TelepathicGrunt** [comment]
The reason the nether villages had piglins in the first place was because Villagers are an Overworld specific mob. They really don't belong in the Nether. Hence why I used Piglins as the replacement lol. Though you can use a datapack to replace the piglins with villages and add a nether portal pieces to the village like that's how they got to the nether in the first place! I dont think it's too many files to replace but just ask if you need help with making the datapack.

As for the end village, I did thought about that a long time ago. However, Villagers really do not fit in the End and looks very out of place. The only other humanoid mob is the Endermen and they are too tall for the doors. Furthermore, this is what happens to villages in The End when I was testing the idea originally lol
![image](https://user-images.githubusercontent.com/40846040/101285646-5b47b880-37b4-11eb-8b4c-0adf88c751dc.png)

If Mojang does a revamp of The End and adds a 1 or 2 block high humanoid mob, I can look into doing an End Village again as it would seem less out of place if it had mobs native to the dimension.

But thank you for the suggestions tho!
