### ISSUE TITLE
make warped and crimson outpost floor material nether brick

### ISSUE THREAD

**Issue by RyanCR03** [TelepathicGrunt/RepurposedStructures-Fabric#84]
why is the floor of the crimson and warped outpost made of the opposite wood, so I had the idea of replacing it with nether bricks as both the crimson and warped forests have netherrack that can be smelted into nether bricks.

**Comment by TelepathicGrunt** [comment]
They have the opposite wood for the floor to mimic the vanilla outposts design. vanilla outposts uses dark oak wood for the outsides but birch wood for the flooring inside. It is intentional design. 

However, you can change the wood types with a datapack. Here's a quick one I made that works with the latest repurposed structures version. All I did was just edit the nbt files to swap the planks lol.
[Repurposed_Structures-Nether_Outposts.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/6043909/Repurposed_Structures-Nether_Outposts.zip)

Hope this helps!
