### ISSUE TITLE
End Dungeon Shulker Boxes too rare

### ISSUE THREAD

**Issue by RyanCR03** [TelepathicGrunt/RepurposedStructures-Fabric#85]
the dungeons in the end that spawn endermites are completely useless there's no risk and no reward nothing that would make sense for a dungeon.

**Comment by TelepathicGrunt** [comment]
The issue is that vanilla only have like 2/3 mobs that fit the end. If you have other mods on that adds more dangerous end themed mobs, you can add that mob to the end dungeon's spawners by editing this datapack. Otherwise, you can turn off the end dungeons by config or nerf its loot with a loottable datapack. 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/tag/0.0.5

There's a few options you have here. I can't really do much without redesigning the dungeon and that defeats the purpose of my mod. The other thing I could do is just add more spawners but that feels like a cop-out. Then again, the end isn't really that dangerous tbh outside the main end island. Only falling into the void is the danger

**Comment by RyanCR03** [comment]
you could turn up the spawn rate on the spawner so the whole idea would be getting swarmed with endermites. I'm more complaining about the fact that there is  no chests in the dungeons

**Comment by TelepathicGrunt** [comment]
Ohh. The dungeon does spawn a Shulker Box that will contain loot but it is rarer than regular dungeon chests. Looking at my old code, I have it where it will pick 0 to 4 random spots on the floor, check if the spots have only one side with solid blocks, and then spawn the shulker box if so. 

...and now I see my code wont ever spawn a shulker box on the corners of the dungeon lol. 
That I gotta fix. Once that's fixed, the dungeon will have a bit higher chance of having the shulker box

**Comment by TelepathicGrunt** [comment]
v1.8.6 is now out and make shulker boxes more common and have a spawner below them
