### ISSUE TITLE
Not compatible with Better Traders by cyborg_pigeon. (Fabric v1.8.3)

### ISSUE THREAD

**Issue by LunaEversor** [TelepathicGrunt/RepurposedStructures-Fabric#88]
I'm not sure which mod author to report this issue to. It appears that Better Wandering Traders and Repurposed Structures are incompatible. If both mods are installed at the same time, the traders will not display the loot table from Better Wandering Traders.

**Comment by TelepathicGrunt** [comment]
Are you sure this is related to repurposed structures? Cause I do not touch wandering traders at all. In fact, I only touch the cartographer trades by using Fabric API's api.
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/d1c5b38f8df9561735c8608844b5fc6ced2ba4e1/src/main/java/com/telepathicgrunt/repurposedstructures/misc/MobMapTrades.java#L15-L29

**Comment by TelepathicGrunt** [comment]
I see the issue. It's because Better Wandering Traders is not using Fabric API's already existing hook to add to Wandering Traders.
`TradeOfferHelper.registerWanderingTraderOffers`

When I call TradeOfferHelper.registerVillagerOffers, Fabric API adds my trades and then calls this method which resets the Wandering Trader back to its default trades because Better Wandering Traders never used the API add trades. I'll let that mod know to use the API. 
![image](https://user-images.githubusercontent.com/40846040/109737190-9ed37800-7b93-11eb-8b1d-1e7a343136c9.png)

**Comment by LunaEversor** [comment]
Alright, thank you for looking into it. I wasn't sure what was going on, or who I should be reporting the issue to. As much as I like making the useless traders useful, I think I'll stay with Repurposed Structures for now. It adds so much more than a bartering mechanic. Thanks again.

**Comment by TelepathicGrunt** [comment]
Dang it's been a month. I hope they didn't abandoned their mod. rip
Fabric API is looking into making their trade modification system safer so fabric api could fix this incompat in the future

**Comment by TelepathicGrunt** [comment]
Ok uhhh. The Fabric API for adding trades to villagers is actually broken and duplicates trades like crazy. I release v1.10.4 repurposed structures that no longer uses the api and just adds my trades to villagers directly. This means latest Repurposed Structures now works with Better Traders and I'll be discouraging people from using the trade API from Fabric API until they fix that broken mess lol
